use avif_rust::av1::{parse_frame_header, parse_sequence_header, parse_tile_group};

// Reduced-still, 16x16, 8-bit 4:4:4 identity-GBR sequence header generated by
// libaom. The frame vector keeps only the uncompressed header and one payload
// byte so header alignment can be tested independently of entropy decoding.
const SEQUENCE_HEADER: &[u8] = &[0x38, 0x0c, 0xff, 0xd8, 0x40, 0x43, 0x40, 0x08];
const FRAME_HEADER_AND_PAYLOAD: &[u8] = &[0x44, 0x00, 0x00, 0xc2];

#[test]
fn reduced_still_header_reads_screen_content_fields_before_frame_size() {
    let sequence = parse_sequence_header(SEQUENCE_HEADER).unwrap();
    assert!(sequence.reduced_still_picture_header);
    assert_eq!(sequence.seq_force_screen_content_tools, 2);
    assert_eq!(sequence.seq_force_integer_mv, 2);

    let frame = parse_frame_header(FRAME_HEADER_AND_PAYLOAD, &sequence).unwrap();

    assert!(!frame.disable_cdf_update);
    assert!(frame.allow_screen_content_tools);
    assert_eq!(frame.force_integer_mv, 0);
    assert!(!frame.allow_intrabc);
    assert_eq!(frame.frame_width, 16);
    assert_eq!(frame.frame_height, 16);
    assert_eq!(frame.base_q_idx, 0);
    assert_eq!(frame.uncompressed_header_bits, 20);
    assert_eq!(frame.payload_after_header_offset, 3);
}

#[test]
fn reduced_still_header_leaves_zero_alignment_bits_for_tile_group() {
    let sequence = parse_sequence_header(SEQUENCE_HEADER).unwrap();
    let frame = parse_frame_header(FRAME_HEADER_AND_PAYLOAD, &sequence).unwrap();

    let tile_group = parse_tile_group(
        FRAME_HEADER_AND_PAYLOAD,
        frame.uncompressed_header_bits,
        &frame.tile_info,
    )
    .unwrap();

    assert_eq!(tile_group.data_start_offset, 3);
    assert_eq!(tile_group.tiles.len(), 1);
    assert_eq!(tile_group.tiles[0].offset, 3);
    assert_eq!(tile_group.tiles[0].len, 1);
}
